language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t kjarisk/docker-frontreact -f Dockerfile.dev .

script:
  - docker run -e CI=true kjarisk/docker-frontreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-frontreact"
  env: "DockerFrontreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-190343677142"
  bucket_path: "docker-frontreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY